AIrjen/OneButtonPrompt

README.md

With trailish slash not working when install from URL

Remove trailish slash in install URL

---

scripts/onebuttonprompt.py

Added Workflow prompt field, and send to Workflow prompt buttons

Workflow mode improvement

---

scripts/onebuttonprompt.py

Fighting with Gradio

---

README.md
csvfiles/concept_prefix.csv
csvfiles/concept_suffix.csv
scripts/onebuttonprompt.py
user_guides/override_subject_and_infinite_variations.md
user_guides/prompt_compounder_and_regional_prompter_to_create_insane_images.md
user_guides/wildcards_and_dynamic_prompts_extension.md

Small fixes and adjustments
Documentation for Prompt Compounder and Regional Prompter
Documentation for using wildcards and Dynamic Prompts

Docs docs docs docs everybodyyy

---

build_dynamic_prompt.py
prompttester.py
scripts/onebuttonprompt.py

Moved cleaning into seperate function, now also works with calling for Artists only mode

Prefix now working with automatic mode

---

build_dynamic_prompt.py
call_img2img.py
csvfiles/special_lists/animaladditions.csv
csvfiles/special_lists/buildoutfit.csv

Made templates more rare and added a print message
theoretical maybe fix for an issue with ultimate upscale
Added some minor additions in some logic for outfit and animal

Mini update

---

build_dynamic_prompt.py
csvfiles/buildings.csv
csvfiles/colorscheme.csv
csvfiles/concept_prefix.csv
csvfiles/containers.csv
csvfiles/descriptors.csv
csvfiles/manwoman.csv
csvfiles/manwomanrelations.csv
csvfiles/musicgenres.csv
csvfiles/special_lists/humanadditions.csv
csvfiles/special_lists/overalladditions.csv
csvfiles/vomit.csv
csvfiles/waterlocations.csv
model_lists.py
prompttester.py

Also first workaround for upscalers not loading in WebUI 1.4 / Vlad

Minor updates and wildcards

---

build_dynamic_prompt.py

Storing LoRA's first and then putting them back AFTER we clean up the prompt, so they remain the same

LoRA stability

---

scripts/onebuttonprompt.py

Lots of user feedback from Olivio's video. Needed some more text to start clarifications more.

Add more descriptions

---

model_lists.py

HELLO THERE!

---

call_extras.py
call_img2img.py
call_txt2img.py

Trying a hardcoded for for issue 77

Hotfix for files

---

scripts/onebuttonprompt.py

Hello there
Really fun script you made there. Please check out some minor fixes I made. You might be intrested in them.
To clarify about the batch save thing. This problem happens if you run batch size and batch count > 1.

Fix batch save seed gen progress bar

---

model_lists.py

Added dynamic sampler loading also for img2img

Add dynamic samplers also for img2img

---

build_dynamic_prompt.py

Makes it so it works on capital letters etc.

added strip and lower to the antilist logic

---

OneButtonPromptNodes.py
build_dynamic_prompt.py
csvfiles/card_names.csv
scripts/onebuttonprompt.py

Huge TCG card name list update. Lots of fun!

Added card names list

---

build_dynamic_prompt.py
csvfiles/outfitvomit.csv
csvfiles/special_lists/buildoutfit.csv
prompttester.py
scripts/onebuttonprompt.py

Fix for the open issues + some minor fixes

Minor set of bugfixes

---

OneButtonPromptNodes.py
build_dynamic_prompt.py
comfyui_workflow_examples/SDXL_OBP_Refiner.json
comfyui_workflow_examples/SDX_OBP_NoRefiner.json
csv_reader.py
csvfiles/card_names.csv
csvfiles/concept_prefix.csv
csvfiles/jobs.csv
csvfiles/special_lists/negativewords.csv
csvfiles/templates/styles.csv
main.py
negativeprompttester.py
prompttester.py
scripts/onebuttonprompt.py
user_guides/auto_negative_prompt.md
user_guides/comfyui_integration.md
userfiles/negativewords_addon_sample.csv

Added Auto Negative Prompt
(and some other changes, fixes and improvements)

Big negative update

---

build_dynamic_prompt.py

Hello. 
Current divider for parts of a prompt breaks [Lora Control ](https://github.com/cheald/sd-webui-loractl.git) extension divider. It's just a simple fix to be sure that single "@" is not stripped from prompts.

Replace divider for more uniquiness

---

csv_reader.py
enhancepositivetester.py
negativeprompttester.py
prompttester.py
promptvarianttester.py
upscaler.py

custom_nodes load time from 0.8 seconds to 0.0
0.0 seconds: /workspace/ComfyUI/custom_nodes/OneButtonPrompt

Some test codes do not need to be executed every time

---

build_dynamic_prompt.py
csvfiles/imagetypes_anime.csv
prompttester.py

minor bugfixes
More support for anime model mode

last changes
